language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
#  - nightly

matrix:
  include:
    - install: composer install --prefer-source --dev
    - install: "sed -i 's/\"phpseclib\\/phpseclib\": \"[^\"]*/\"phpseclib\\/phpseclib\": \"2.0.0/' && composer install --prefer-source --dev"
