language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

dist: trusty

env:
  - PHPSECLIB='^2.0 !=2.0.8'
  - PHPSECLIB="2.0.0"
  - PHPSECLIB="2.0.1"
  - PHPSECLIB="2.0.2"
  - PHPSECLIB="2.0.3"
  - PHPSECLIB="2.0.4"
  - PHPSECLIB="2.0.5"
  - PHPSECLIB="2.0.6"
  - PHPSECLIB="2.0.7"
  - PHPSECLIB="2.0.9"
  - PHPSECLIB="2.0.10"
  - PHPSECLIB="2.0.11"

matrix:
  allow_failures:
    - php: 7.1
    - php: 7.2
    
  fast_finish: true

before_script: 'sed -i "s/\"phpseclib\/phpseclib\": \"[^\"]*/\"phpseclib\/phpseclib\": \"$PHPSECLIB/" composer.json && composer install --prefer-source --dev'
